### PR TITLE
#31: implement `find_with_closure`

### PR DESCRIPTION
**Pull request by UARTman**
This commit also fixes a clippy error in my IDE, but I could push the fix separately.

### CODE REVIEW

**Comment by yegor256** [comment]
@UARTman no tests? it's important to have a unit tests, on top of the Rustdoc you already have: they are easier to run from IDE and they are more canonical approach to test.

**Comment by UARTman** [comment]
Which cases should I implement besides the one I already wrote in a doctest?

**Comment by yegor256** [comment]
@UARTman it could be something similar to the snippet in the doctest block

**Comment by yegor256** [comment]
@UARTman when you post a message addressed to me, please mention my GitHub nickname (like I'm doing in this message). without this, I simply don't see your messages.

**Comment by yegor256** [comment]
@UARTman ready? (when your PR is ready for another round of code review, ping the reviewer; otherwise, they won't know that you are ready and PR will stay unattended)

**Comment by UARTman** [comment]
@yegor256 Yes, I think I'm ready. Writing the tests helped me understand the planned behavior of `find` and fix a big logic error in my code.

Also, I improved the `Sodg::split_a()` - there is no need for `String`s to go in where `&str` is enough, which reduces on cloning. There's another couple of improvements I might make to it later, such as using the iterator directly instead of collecting it into a vector.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
